import "@app/styles/globals.css";

import { type Metadata } from "next";

import { TRPCReactProvider } from "@app/trpc/react";
import { MainLayout } from "@app/components/layouts/main";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <MainLayout>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </MainLayout>
      </body>
    </html>
  );
}
